// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NowPlayingInfo.proto

package com.google.protobuf;

public final class NowPlayingProto {
  private NowPlayingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SongMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protofiles.SongMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string artist = 1;</code>
     */
    boolean hasArtist();
    /**
     * <code>required string artist = 1;</code>
     */
    java.lang.String getArtist();
    /**
     * <code>required string artist = 1;</code>
     */
    com.google.protobuf.ByteString
        getArtistBytes();

    /**
     * <code>required string title = 3;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 3;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 3;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional bytes songIcon = 4;</code>
     */
    boolean hasSongIcon();
    /**
     * <code>optional bytes songIcon = 4;</code>
     */
    com.google.protobuf.ByteString getSongIcon();

    /**
     * <code>optional string album = 5;</code>
     */
    boolean hasAlbum();
    /**
     * <code>optional string album = 5;</code>
     */
    java.lang.String getAlbum();
    /**
     * <code>optional string album = 5;</code>
     */
    com.google.protobuf.ByteString
        getAlbumBytes();

    /**
     * <code>optional string dataURI = 6;</code>
     */
    boolean hasDataURI();
    /**
     * <code>optional string dataURI = 6;</code>
     */
    java.lang.String getDataURI();
    /**
     * <code>optional string dataURI = 6;</code>
     */
    com.google.protobuf.ByteString
        getDataURIBytes();
  }
  /**
   * Protobuf type {@code protofiles.SongMessage}
   */
  public static final class SongMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protofiles.SongMessage)
      SongMessageOrBuilder {
    // Use SongMessage.newBuilder() to construct.
    private SongMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SongMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SongMessage defaultInstance;
    public static SongMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SongMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SongMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              artist_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              songIcon_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              album_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              dataURI_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.NowPlayingProto.internal_static_protofiles_SongMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.NowPlayingProto.internal_static_protofiles_SongMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.NowPlayingProto.SongMessage.class, com.google.protobuf.NowPlayingProto.SongMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SongMessage> PARSER =
        new com.google.protobuf.AbstractParser<SongMessage>() {
      public SongMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SongMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SongMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ARTIST_FIELD_NUMBER = 1;
    private java.lang.Object artist_;
    /**
     * <code>required string artist = 1;</code>
     */
    public boolean hasArtist() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string artist = 1;</code>
     */
    public java.lang.String getArtist() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          artist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string artist = 1;</code>
     */
    public com.google.protobuf.ByteString
        getArtistBytes() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.Object title_;
    /**
     * <code>required string title = 3;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SONGICON_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString songIcon_;
    /**
     * <code>optional bytes songIcon = 4;</code>
     */
    public boolean hasSongIcon() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes songIcon = 4;</code>
     */
    public com.google.protobuf.ByteString getSongIcon() {
      return songIcon_;
    }

    public static final int ALBUM_FIELD_NUMBER = 5;
    private java.lang.Object album_;
    /**
     * <code>optional string album = 5;</code>
     */
    public boolean hasAlbum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string album = 5;</code>
     */
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          album_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string album = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAURI_FIELD_NUMBER = 6;
    private java.lang.Object dataURI_;
    /**
     * <code>optional string dataURI = 6;</code>
     */
    public boolean hasDataURI() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string dataURI = 6;</code>
     */
    public java.lang.String getDataURI() {
      java.lang.Object ref = dataURI_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataURI_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dataURI = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDataURIBytes() {
      java.lang.Object ref = dataURI_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataURI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      artist_ = "";
      title_ = "";
      songIcon_ = com.google.protobuf.ByteString.EMPTY;
      album_ = "";
      dataURI_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasArtist()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getArtistBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, songIcon_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getAlbumBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getDataURIBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getArtistBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, songIcon_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAlbumBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDataURIBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protobuf.NowPlayingProto.SongMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protobuf.NowPlayingProto.SongMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protobuf.NowPlayingProto.SongMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protofiles.SongMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protofiles.SongMessage)
        com.google.protobuf.NowPlayingProto.SongMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.NowPlayingProto.internal_static_protofiles_SongMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.NowPlayingProto.internal_static_protofiles_SongMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.NowPlayingProto.SongMessage.class, com.google.protobuf.NowPlayingProto.SongMessage.Builder.class);
      }

      // Construct using com.google.protobuf.NowPlayingProto.SongMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        artist_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        songIcon_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        album_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        dataURI_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.NowPlayingProto.internal_static_protofiles_SongMessage_descriptor;
      }

      public com.google.protobuf.NowPlayingProto.SongMessage getDefaultInstanceForType() {
        return com.google.protobuf.NowPlayingProto.SongMessage.getDefaultInstance();
      }

      public com.google.protobuf.NowPlayingProto.SongMessage build() {
        com.google.protobuf.NowPlayingProto.SongMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.NowPlayingProto.SongMessage buildPartial() {
        com.google.protobuf.NowPlayingProto.SongMessage result = new com.google.protobuf.NowPlayingProto.SongMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.artist_ = artist_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.songIcon_ = songIcon_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.album_ = album_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dataURI_ = dataURI_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.NowPlayingProto.SongMessage) {
          return mergeFrom((com.google.protobuf.NowPlayingProto.SongMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.NowPlayingProto.SongMessage other) {
        if (other == com.google.protobuf.NowPlayingProto.SongMessage.getDefaultInstance()) return this;
        if (other.hasArtist()) {
          bitField0_ |= 0x00000001;
          artist_ = other.artist_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasSongIcon()) {
          setSongIcon(other.getSongIcon());
        }
        if (other.hasAlbum()) {
          bitField0_ |= 0x00000008;
          album_ = other.album_;
          onChanged();
        }
        if (other.hasDataURI()) {
          bitField0_ |= 0x00000010;
          dataURI_ = other.dataURI_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasArtist()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.NowPlayingProto.SongMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.NowPlayingProto.SongMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object artist_ = "";
      /**
       * <code>required string artist = 1;</code>
       */
      public boolean hasArtist() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string artist = 1;</code>
       */
      public java.lang.String getArtist() {
        java.lang.Object ref = artist_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            artist_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string artist = 1;</code>
       */
      public com.google.protobuf.ByteString
          getArtistBytes() {
        java.lang.Object ref = artist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          artist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string artist = 1;</code>
       */
      public Builder setArtist(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        artist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string artist = 1;</code>
       */
      public Builder clearArtist() {
        bitField0_ = (bitField0_ & ~0x00000001);
        artist_ = getDefaultInstance().getArtist();
        onChanged();
        return this;
      }
      /**
       * <code>required string artist = 1;</code>
       */
      public Builder setArtistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        artist_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 3;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string title = 3;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString songIcon_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes songIcon = 4;</code>
       */
      public boolean hasSongIcon() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes songIcon = 4;</code>
       */
      public com.google.protobuf.ByteString getSongIcon() {
        return songIcon_;
      }
      /**
       * <code>optional bytes songIcon = 4;</code>
       */
      public Builder setSongIcon(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        songIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes songIcon = 4;</code>
       */
      public Builder clearSongIcon() {
        bitField0_ = (bitField0_ & ~0x00000004);
        songIcon_ = getDefaultInstance().getSongIcon();
        onChanged();
        return this;
      }

      private java.lang.Object album_ = "";
      /**
       * <code>optional string album = 5;</code>
       */
      public boolean hasAlbum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string album = 5;</code>
       */
      public java.lang.String getAlbum() {
        java.lang.Object ref = album_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            album_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string album = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumBytes() {
        java.lang.Object ref = album_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          album_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string album = 5;</code>
       */
      public Builder setAlbum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        album_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string album = 5;</code>
       */
      public Builder clearAlbum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        album_ = getDefaultInstance().getAlbum();
        onChanged();
        return this;
      }
      /**
       * <code>optional string album = 5;</code>
       */
      public Builder setAlbumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        album_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataURI_ = "";
      /**
       * <code>optional string dataURI = 6;</code>
       */
      public boolean hasDataURI() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string dataURI = 6;</code>
       */
      public java.lang.String getDataURI() {
        java.lang.Object ref = dataURI_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataURI_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dataURI = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDataURIBytes() {
        java.lang.Object ref = dataURI_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataURI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dataURI = 6;</code>
       */
      public Builder setDataURI(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dataURI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataURI = 6;</code>
       */
      public Builder clearDataURI() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dataURI_ = getDefaultInstance().getDataURI();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataURI = 6;</code>
       */
      public Builder setDataURIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dataURI_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protofiles.SongMessage)
    }

    static {
      defaultInstance = new SongMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protofiles.SongMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protofiles_SongMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protofiles_SongMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024NowPlayingInfo.proto\022\nprotofiles\"^\n\013So" +
      "ngMessage\022\016\n\006artist\030\001 \002(\t\022\r\n\005title\030\003 \002(\t" +
      "\022\020\n\010songIcon\030\004 \001(\014\022\r\n\005album\030\005 \001(\t\022\017\n\007dat" +
      "aURI\030\006 \001(\tB&\n\023com.google.protobufB\017NowPl" +
      "ayingProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protofiles_SongMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protofiles_SongMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protofiles_SongMessage_descriptor,
        new java.lang.String[] { "Artist", "Title", "SongIcon", "Album", "DataURI", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
