// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: btmessage.proto

package com.google.protobuf;

public final class BluetoothProto {
  private BluetoothProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BTMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protofiles.BTMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 messageCommand = 5;</code>
     */
    boolean hasMessageCommand();
    /**
     * <code>required int32 messageCommand = 5;</code>
     */
    int getMessageCommand();

    /**
     * <code>optional bytes messageByteString = 2;</code>
     */
    boolean hasMessageByteString();
    /**
     * <code>optional bytes messageByteString = 2;</code>
     */
    com.google.protobuf.ByteString getMessageByteString();
  }
  /**
   * Protobuf type {@code protofiles.BTMessage}
   */
  public static final class BTMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protofiles.BTMessage)
      BTMessageOrBuilder {
    // Use BTMessage.newBuilder() to construct.
    private BTMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BTMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BTMessage defaultInstance;
    public static BTMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BTMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BTMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              messageByteString_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000001;
              messageCommand_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_protofiles_BTMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_protofiles_BTMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
                  com.google.protobuf.BluetoothProto.BTMessage.class, com.google.protobuf.BluetoothProto.BTMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BTMessage> PARSER =
        new com.google.protobuf.AbstractParser<BTMessage>() {
      public BTMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BTMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<BTMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGECOMMAND_FIELD_NUMBER = 5;
    private int messageCommand_;
    /**
     * <code>required int32 messageCommand = 5;</code>
     */
    public boolean hasMessageCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 messageCommand = 5;</code>
     */
    public int getMessageCommand() {
      return messageCommand_;
    }

    public static final int MESSAGEBYTESTRING_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString messageByteString_;
    /**
     * <code>optional bytes messageByteString = 2;</code>
     */
    public boolean hasMessageByteString() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes messageByteString = 2;</code>
     */
    public com.google.protobuf.ByteString getMessageByteString() {
      return messageByteString_;
    }

    private void initFields() {
      messageCommand_ = 0;
      messageByteString_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, messageByteString_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(5, messageCommand_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, messageByteString_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, messageCommand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protobuf.BluetoothProto.BTMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protobuf.BluetoothProto.BTMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protobuf.BluetoothProto.BTMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protofiles.BTMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protofiles.BTMessage)
        com.google.protobuf.BluetoothProto.BTMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_protofiles_BTMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_protofiles_BTMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.google.protobuf.BluetoothProto.BTMessage.class, com.google.protobuf.BluetoothProto.BTMessage.Builder.class);
      }

      // Construct using com.google.protobuf.BluetoothProto.BTMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageCommand_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageByteString_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_protofiles_BTMessage_descriptor;
      }

      public com.google.protobuf.BluetoothProto.BTMessage getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public com.google.protobuf.BluetoothProto.BTMessage build() {
        com.google.protobuf.BluetoothProto.BTMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.BluetoothProto.BTMessage buildPartial() {
        com.google.protobuf.BluetoothProto.BTMessage result = new com.google.protobuf.BluetoothProto.BTMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageCommand_ = messageCommand_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageByteString_ = messageByteString_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.BluetoothProto.BTMessage) {
          return mergeFrom((com.google.protobuf.BluetoothProto.BTMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.BluetoothProto.BTMessage other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasMessageCommand()) {
          setMessageCommand(other.getMessageCommand());
        }
        if (other.hasMessageByteString()) {
          setMessageByteString(other.getMessageByteString());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.BluetoothProto.BTMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.BluetoothProto.BTMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int messageCommand_ ;
      /**
       * <code>required int32 messageCommand = 5;</code>
       */
      public boolean hasMessageCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 messageCommand = 5;</code>
       */
      public int getMessageCommand() {
        return messageCommand_;
      }
      /**
       * <code>required int32 messageCommand = 5;</code>
       */
      public Builder setMessageCommand(int value) {
        bitField0_ |= 0x00000001;
        messageCommand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 messageCommand = 5;</code>
       */
      public Builder clearMessageCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageCommand_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messageByteString_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes messageByteString = 2;</code>
       */
      public boolean hasMessageByteString() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes messageByteString = 2;</code>
       */
      public com.google.protobuf.ByteString getMessageByteString() {
        return messageByteString_;
      }
      /**
       * <code>optional bytes messageByteString = 2;</code>
       */
      public Builder setMessageByteString(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        messageByteString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes messageByteString = 2;</code>
       */
      public Builder clearMessageByteString() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageByteString_ = getDefaultInstance().getMessageByteString();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protofiles.BTMessage)
    }

    static {
      defaultInstance = new BTMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protofiles.BTMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protofiles_BTMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protofiles_BTMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017btmessage.proto\022\nprotofiles\">\n\tBTMessa" +
      "ge\022\026\n\016messageCommand\030\005 \002(\005\022\031\n\021messageByt" +
      "eString\030\002 \001(\014B/\n\035com.rufuslabs.protocolb" +
      "uffersB\016BluetoothProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protofiles_BTMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protofiles_BTMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protofiles_BTMessage_descriptor,
        new String[] { "MessageCommand", "MessageByteString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
